---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-persistent-volume
spec:
  storageClassName: "standard"
  capacity:
    storage: 5Gi
  hostPath:
    path: "/host/test-persistent-volume/"
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: test-persistent-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-01-05 - 16:55:05 +0000
  labels:
    app.kubernetes.io/name: test-monitoring
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: test-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-monitoring
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-01-05 - 16:55:05 +0000
      labels:
        app.kubernetes.io/name: test-monitoring
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      initContainers:
        - name: elastic-java-agent
          image: docker.elastic.co/observability/apm-agent-java:1.34.1
          volumeMounts:
            - mountPath: /home
              name: test-storage
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          command: [ 'cp', '-v', '/usr/agent/elastic-apm-agent.jar', '/home/code-elastic-apm-agent.jar' ]
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ELASTIC_APM_SERVER_URL
              value: "https://apm-server-apm-http.elastic.svc.cluster.local:8200"
            - name: ELASTIC_APM_SERVICE_NAME
              value: "code-with-quarkus"
            - name: ELASTIC_APM_APPLICATION_PACKAGES
              value: "org.acme"
            - name: ELASTIC_APM_ENVIRONMENT
              value: code-with-quarkus
            - name: ELASTIC_APM_LOG_LEVEL
              value: DEBUG
            - name: ELASTIC_APM_VERIFY_SERVER_CERT
              value: "false"
            - name: ELASTIC_APM_ENABLE_EXPERIMENTAL_INSTRUMENTATIONS
              value: "true"
            - name: ELASTIC_APM_SECRET_TOKEN
              value: "zEQ3642k2C0tDT58x2K2emLz"
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/home/code-elastic-apm-agent.jar
          image: gmacini/test-monitoring:1.0.0-SNAPSHOT
          imagePullPolicy: Never
          name: test-monitoring
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /home
              name: test-storage
              readOnly: false
      volumes:
        - name: test-storage
          persistentVolumeClaim:
            claimName: test-volume
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-01-05 - 16:55:05 +0000
  labels:
    app.kubernetes.io/name: test-monitoring
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: test-monitoring
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: test-monitoring
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
